name: Go CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.18"

      - name: Verify Dependencies
        run: go mod verify

      - name: Build the Library
        run: go build -v ./...

      - name: Run Vet (Static Analysis)
        run: go vet ./...

      - name: Run Tests
        run: go test -v ./...
